### ISSUE TITLE
Recording is crash when entering vehicle

### ISSUE THREAD

**Issue by thenoobi** [elsewhat/gtav-mod-scene-director#2]
This very good mod, but when Iam entering vehicle, crash is happen:
error FATAL: Can't find native 0x36D782F68B309BDA

Please fix this, im realy love this mod!
Thanks before :)

**Comment by elsewhat** [comment]
Hi,

You have an old version of GTA which is missing natives for newer functions. As they do not exist in your version, the mod crashes. Upgrade gta

**Comment by thenoobi** [comment]
Thankks for your support.
Cheers
