### ISSUE TITLE
How can I get mesh from GTAV ?

### ISSUE THREAD

**Issue by SWWdz** [elsewhat/gtav-mod-scene-director#6]
I'm interested in how to get a mesh from GTAV, but I am a bit questionable about the actual implementation of getting GTAV mesh.  
I've learned some functions through the DirectX developer documentation, such as CreateGeometryShaderWithStreamOutput(), but I don't know the parameters passed in, so do you have any references or code to refer to? I would be grateful!

**Comment by elsewhat** [comment]
Sorry, I've only used the Script Hook V which gives access at a level adapted from scripting 
https://gtaforums.com/topic/932648-script-hook-v/

**Comment by SWWdz** [comment]
Thanks for your advice!
